### ISSUE TITLE
Kmozillahelper uses excessive cpu after upgrade to opensuse leap 42.3

### ISSUE THREAD

**Issue by pensionado** [openSUSE/kmozillahelper#17]
Since upgrading to opensuse leap 42.3, opening up a large (1000+ lines) email in thunderbird seemingly hangs. Looking at active processes I can see that kmozillahelper (below thunderbird) is using one of the cores 100% for considerable amount of time. Only happens on email with LARGE text contents. kmozillahelper version 5.0.1-1.3, thunderbird 52.2.1-42.1. Please advice how to collect diagnostics if required for solution.

**Comment by Vogtinator** [comment]
That's a bug in thunderbird and can't really be fixed in kmozillahelper: https://bugzilla.opensuse.org/show_bug.cgi?id=1037806

It would be possible to speed up the process a bit by optimizing the KDE lib that is used, but that's only an ugly workaround as thunderbird does thousands of garbage queries.
